name: Run daily logons
on:
  schedule:
    - cron: '37 7 * * *'
  push: []

jobs:
  logons:
    if: "!contains(github.event.head_commit.message, 'Monthly keep-alive')"
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout configuration
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true

      - name: Write out entry.dat file
        run: |
          mkdir lich/data
          echo "$ENTRY_DAT" > lich/data/entry.dat
        shell: bash
        env:
          ENTRY_DAT: ${{secrets.ENTRY_DAT}}

      - name: Run logon script
        uses: nick-fields/retry@v3
        with:
          command: bundle exec bin/login --rewards --login
          timeout_minutes: 5
          max_attempts: 3
