name: Run daily logons
on:
  schedule:
    - cron: '37 8 * * *'
  push: []

jobs:
  logons:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout configuration
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Install sqlite3 gem
        run: gem install sqlite3 tty-command mechanize --no-document

      - name: Make data dir
        run: mkdir lich/data
        shell: bash

      - name: Write out entry.dat file
        run: 'echo "$ENTRY_DAT" > lich/data/entry.dat'
        shell: bash
        env:
          SSH_KEY: ${{secrets.ENTRY_DAT}}

      - name: Run logon script
        run: bin/login --rewards --login
