name: Run daily logons
on:
  workflow_dispatch:

jobs:
  logons:
    if: "!contains(github.event.head_commit.message, 'Monthly keep-alive')"
    timeout-minutes: 2
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout configuration
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Download latest rewards release
        run: wget https://github.com/ondreian/rewards.cr/releases/download/v0.3.2/rewards
        
      - name: run rewards
        run: ./rewards accounts.csv
