name: New accounts test
on:
  workflow_dispatch:

jobs:
  logons:
    if: "!contains(github.event.head_commit.message, 'Monthly keep-alive')"
    timeout-minutes: 2
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout configuration
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Write out accounts file
        run: |
          echo $ACCOUNTSTEST >> accounts.csv
        shell: bash
        env:
          ACCOUNTSTEST : ${{secrets.ACCOUNTSTEST}}

      - name: Download latest rewards release
        run: |
          wget https://github.com/ondreian/rewards.cr/releases/download/v0.3.2/rewards
          chmod +x rewards
        
      - name: Run rewards
        run: ./rewards accounts.csv
