name: Run daily logons
on:
  schedule:
    on_demand:
  push: []

jobs:
  logons:
    if: "!contains(github.event.head_commit.message, 'Monthly keep-alive')"
    timeout-minutes: 2
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout configuration
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true

      - name: Write out entry.dat file
        run: |
          mkdir lich/data
          echo "$ENTRY_DAT" > lich/data/entry.dat
        shell: bash
        env:
          ENTRY_DAT: ${{secrets.ENTRY_DAT}}

      - name: Run logon script
        run: bundle exec bin/login --rewards --login
